#!/usr/bin/env bash

set -euo pipefail

source "${0%/*}/docker-healthcheck.conf"

status=0
server=@localhost

for host in "${hosts[@]}"; do
  qualified="$host$domain"

  printf 'Looking up %s\n' "$qualified"
  if ! output="$(dig +short "$qualified" "$server")"; then
    status=1
  fi

  [[ -z "$output" ]] && status=2

  printf '%s\n' "$output"
done

exit "$status"
