version: "2.4"

services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - type: volume
        source: redis-data
        target: /data
    healthcheck:
      test: redis-cli -h localhost ping | grep -xq PONG || exit 1
      start_period: 5s
    sysctls:
      net.core.somaxconn: 512

  dnsmasq:
    image: agross/dnsmasq
    build:
      context: dnsmasq
      dockerfile: Dockerfile
    network_mode: host
    privileged: true
    volumes:
      - type: volume
        source: dnsmasq-leases
        target: /dnsmasq-leases
      - type: bind
        source: ./dnsmasq/conf.d
        target: /etc/dnsmasq.d
        read_only: true

  app:
    image: agross/anyrouter
    build:
      context: app
      dockerfile: Dockerfile
    network_mode: host
    privileged: true
    depends_on:
      dnsmasq:
        condition: service_started
      redis:
        condition: service_healthy

volumes:
  redis-data:
    driver: local
  dnsmasq-leases:
    driver: local
