#!/usr/bin/env sh

# set -e

if [ "$1" = 'run' ]; then
  iptables --list --table nat --numeric

  route -n

  sysctl net.ipv4.ip_forward

  # exec dnsmasq --no-daemon
  exec supervisord --configuration /supervisord.conf
fi

exec "$@"
