#!/usr/bin/env bash

set -euo pipefail

cd "${0%%/*}"

docker=(docker-compose --project-name anyrouter --file docker-compose.yaml)

if [[ "$(uname)" == *Darwin* ]]; then
  docker+=(--file docker-compose.override.macos.yaml)
fi

if [[ "$(uname -a)" == *synology* ]]; then
  docker+=(--file docker-compose.override.synology.yaml)
fi


"${docker[@]}" up --build "$@"
