#!/usr/bin/env bash

set -euo pipefail
docker=(docker-compose --project-name anyrouter)

if [[ "$(uname)" == *Darwin* ]]; then
  docker+=(--file docker-compose.yaml --file docker-compose.override.macos.yaml)
fi

"${docker[@]}" up --build
