#!/usr/bin/env sh

set -e

if [ "$1" = 'run' ]; then
  # Is forwarding enabled?
  sysctl net.ipv4.ip_forward

  # This should print a default gateway.
  route -n

  # Firewall rules.
  iptables --list --numeric --table nat
  iptables --list --numeric --table filter

  exec yarn run start:prod
fi

exec "$@"
