#!/usr/bin/env sh

# set -e

if [ "$1" = 'run' ]; then
  iptables --list --table nat --numeric

  route -n

  ip route --help

  sysctl net.ipv4.ip_forward
  NODE_ENV=production exec yarn run start:prod
fi

exec "$@"
